### ISSUE TITLE
 Sample iSCSI yaml files?

### ISSUE THREAD

**Issue by mathu97** [kubernetes-csi/drivers#103]
Did anyone get the iSCSI driver to work? If so can you provide some sample yaml files?

**Comment by wongma7** [comment]
@j-griffith have you had any success modifying the current driver to run on kubernetes? Any ideas what requirements the spec would have, e.g. is it needed/sufficient to mount /dev? Thanks!

**Comment by j-griffith** [comment]
I started this last week but I've shifted gears a bit and am working on the iscsi connector libs (will need/want that for this driver) first.  I may be able to get back to this at the end of the week or early next week and get something posted.  I'll update here.

BTW, the approach I've taken is to just focus on the CSI driver itself, and not the deployment and ansible playbooks.  You'll need more than just `/dev` I think though; in particular `/lib/modules` and likely `/run` and `/etc/localtime` to keep lvm happy but I haven't dug into things to be sure yet.
