### ISSUE TITLE
Image Pull errror for nfsplugin

### ISSUE THREAD

**Issue by okamototk** [kubernetes-csi/drivers#105]
nfsplugin Image version is invalid.
nfsplugin uses following image:

https://github.com/kubernetes-csi/drivers/blob/master/pkg/nfs/deploy/kubernetes/csi-nodeplugin-nfsplugin.yaml#L40

```
          image: quay.io/k8scsi/nfsplugin:v0.3.0
```

But we can only v0.2.0 in quay:

https://quay.io/repository/k8scsi/nfsplugin?tag=latest&tab=tags

**Comment by haoqing0110** [comment]
@chakri-nelluri @lpabon @rootfs can you help on this?
