### ISSUE TITLE
nodeServer does not implement csi.NodeServer.NodeGetVolumeStats method

### ISSUE THREAD

**Issue by bclau** [kubernetes-csi/drivers#114]
When trying to compile the hostpathplugin driver, it outputs the following error:

    go build -o hostpathplugin.exe github.com/kubernetes-csi/drivers/app/hostpathplugin
    # github.com/kubernetes-csi/drivers/pkg/hostpath
    C:\Users\Test\go\src\github.com\kubernetes-csi\drivers\pkg\hostpath\hostpath.go:123:37: cannot use hp.ns (type *nodeServer) as type csi.NodeServer in argument to s.Start:
        *nodeServer does not implement csi.NodeServer (missing NodeGetVolumeStats method)

It seems that the ``NodeGetVolumeStats`` method has been added to the ``NodeServer`` interface 2 months ago, while the hostpathplugin driver (and the others as well) were last updated 3 months ago.

[1] https://github.com/container-storage-interface/spec/commit/aeca98c2754734e817ee47973e9fc9b22468a5c2

**Comment by Ntr0** [comment]
The vendored spec package also seems to be v1.0.0-rc2 of the spec. So this probably should be updated as well.
