### ISSUE TITLE
Hostpath driver does not need to create targetpath

### ISSUE THREAD

**Issue by lpabon** [kubernetes-csi/drivers#12]
See https://github.com/kubernetes-csi/drivers/blob/master/pkg/hostpath/nodeserver.go#L42

this is required by CSI. If it does not exist, then return an error.

**Comment by rootfs** [comment]
@lpabon where in spec you were referring?

**Comment by lpabon** [comment]
Hi @rootfs , in [NodePublishVolume](https://github.com/container-storage-interface/spec/blob/master/spec.md#nodepublishvolume) the comment for `target_path` says it is the responsibility of the CO to assure that the path exists. So the driver should just check it exists and fail if it does not instead of creating it.
