### ISSUE TITLE
nfsplugin:v0.3.0 image is missing

### ISSUE THREAD

**Issue by ovk** [kubernetes-csi/drivers#126]
The latest NFS plugin [image](https://github.com/kubernetes-csi/drivers/blob/master/pkg/nfs/deploy/kubernetes/csi-nodeplugin-nfsplugin.yaml#L40) is missing in the Quay repository: only v0.2.0 is available.

**Comment by hnwolf** [comment]
I also get the same issue, should we update the version from 0.3.0 to 0.2.0 in the yaml file?
