### ISSUE TITLE
Update CSI sepc to support expand volume 

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes-csi/drivers#151]
Since, current spec is 1.0.0 and does not support  expand volume. I  would to update the spec to 1.1.0 to support it.

**Comment by cwdsuzhou** [comment]
@msau42 I need help

**Comment by msau42** [comment]
Hi @cwdsuzhou, which driver are you interested in adding resizing support for?  We are deprecating this repo and moving each driver to its own separate repository.

**Comment by cwdsuzhou** [comment]
> Hi @cwdsuzhou, which driver are you interested in adding resizing support for? We are deprecating this repo and moving each driver to its own separate repository.

Thank you! I wonder if you will deprecate the csi-common or move it to a separate repository?
Actually, we develop our own csi driver and it is depended on csi-common.

**Comment by msau42** [comment]
Which part if csi-common do you find useful? We were not planning to update csi-common but we can consider pulling out pieces that you find useful

**Comment by cwdsuzhou** [comment]
> Which part if csi-common do you find useful? We were not planning to update csi-common but we can consider pulling out pieces that you find useful

We extended the csi-common overall. Would you like to mv it to a separate repository as a common lib like provisioner-lib?  And I found other drievrs like [alibaba csiplugin](https://github.com/AliyunContainerService/csi-plugin/tree/master/vendor)、[ceph csi](https://github.com/ceph/ceph-csi) also depend on csi-common.
