### ISSUE TITLE
Remove the csi-common package

### ISSUE THREAD

**Issue by lpabon** [kubernetes-csi/drivers#159]
This package is confusing and there is no need to have it. gRPC golang implementations should use the csi.pb.go directly.

**Comment by pohly** [comment]
I fully agree that the package makes no sense. That's why we already changed drivers to not depend on it anymore: https://github.com/kubernetes-csi/csi-driver-host-path/pull/9

However, the entire "drivers" repo is already obsolete. IMHO we don't need to remove individual packages from it.
