### ISSUE TITLE
ReadyToUse state remains to false state during volumesnapshot creation on AWS

### ISSUE THREAD

**Issue by PRatwani** [kubernetes-csi/drivers#168]
While creating a volumesnapshot on AWS its state remains false. Details below:

$ kubectl get volumesnapshot
NAME            READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS    SNAPSHOTCONTENT                                    CREATIONTIME   AGE
test-snapshot   false        ebs-claim                                         test-snapclass   snapcontent-80391d71-0929-4044-9ea9-2b1186685da1                  75m

------
$ kubectl describe volumesnapshot test-snapshot
Name:         test-snapshot
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2021-03-11T07:58:27Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
  Generation:  1
  Managed Fields:
    API Version:  snapshot.storage.k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:source:
          .:
          f:persistentVolumeClaimName:
        f:volumeSnapshotClassName:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-03-11T07:58:27Z
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
      f:status:
        .:
        f:boundVolumeSnapshotContentName:
        f:readyToUse:
    Manager:         snapshot-controller
    Operation:       Update
    Time:            2021-03-11T07:58:27Z
  Resource Version:  1296131
  UID:               80391d71-0929-4044-9ea9-2b1186685da1
Spec:
  Source:
    Persistent Volume Claim Name:  ebs-claim
  Volume Snapshot Class Name:      test-snapclass
Status:
  Bound Volume Snapshot Content Name:  snapcontent-80391d71-0929-4044-9ea9-2b1186685da1
  Ready To Use:                        false
Events:
  Type    Reason            Age   From                 Message
  ----    ------            ----  ----                 -------
  Normal  CreatingSnapshot  75m   snapshot-controller  Waiting for a snapshot default/test-snapshot to be created by the CSI driver.
------------
$ cat snapshot-class.yaml 
apiVersion: snapshot.storage.k8s.io/v1beta1

kind: VolumeSnapshotClass

metadata:

  name: test-snapclass

driver: ebs.csi.aws.com

deletionPolicy: Delete
---------
$ kubectl get pvc,pv
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/ebs-claim   Bound    pvc-cebfa513-f8d3-4235-bda4-0f0bcc5ff0e6   4Gi        RWO            ebs-sc         92m

NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM               STORAGECLASS   REASON   AGE
persistentvolume/pvc-cebfa513-f8d3-4235-bda4-0f0bcc5ff0e6   4Gi        RWO            Delete           Bound    default/ebs-claim   ebs-sc                  91m
----------
$ kubectl get po -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
default       app                                        1/1     Running   1          87m
kube-system   coredns-74ff55c5b-blp4b                    1/1     Running   6          10d
kube-system   coredns-74ff55c5b-f46q5                    1/1     Running   6          10d
kube-system   ebs-csi-controller-85c75df6db-rb6t4        4/4     Running   12         7d2h
kube-system   ebs-csi-controller-85c75df6db-xllbx        4/4     Running   12         7d2h
kube-system   ebs-csi-node-5mz6n                         3/3     Running   9          7d22h
kube-system   ebs-csi-node-6c82x                         3/3     Running   9          7d22h
kube-system   ebs-csi-node-kd5n5                         3/3     Running   9          7d22h
kube-system   etcd-ip-<##>                      1/1     Running   7          10d
kube-system   kube-apiserver-ip-<##>            1/1     Running   9          10d
kube-system   kube-controller-manager-ip-<##>   1/1     Running   7          10d
kube-system   kube-proxy-4kvkx                           1/1     Running   3          10d
kube-system   kube-proxy-8f2cq                           1/1     Running   7          10d
kube-system   kube-proxy-z5pwl                           1/1     Running   3          10d
kube-system   kube-scheduler-ip-<##>            1/1     Running   7          10d
kube-system   snapshot-controller-9f68fdd9-2cqgt         1/1     Running   1          83m
kube-system   snapshot-controller-9f68fdd9-ms4vl         1/1     Running   1          83m
kube-system   weave-net-4lrzt                            2/2     Running   6          10d
kube-system   weave-net-dfdxv                            2/2     Running   6          10d
kube-system   weave-net-tm5t8                            2/2     Running   12         10d
-----------

**Comment by nikhita** [comment]
Closing, this repo is being archived. Please see kubernetes/org#2568 for more details.
