### ISSUE TITLE
Update document to clarify where to get `./_output/nfsplugin`

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-csi/drivers#45]
In https://github.com/kubernetes-csi/drivers/tree/master/pkg/nfs#start-nfs-driver , it mentioned that I can Start NFS driver as following:

```
$ sudo ./_output/nfsplugin --endpoint tcp://127.0.0.1:10000 --nodeid CSINode -v=5
```

Can someone show more detail for where to get the binary of `./_output/nfsplugin`? We should update the document a bit to tell end user how to get this binary.

**Comment by rootfs** [comment]
you need to build the drivers first, run `make` at drivers directory.

**Comment by gyliu513** [comment]
@rootfs shall we update the document a bit by adding `make` section for this?

**Comment by rootfs** [comment]
@gyliu513 good point, PR welcome
