### ISSUE TITLE
The mount source path of nfs  is not correct after deploy pod with  using CSI  NFS driver.

### ISSUE THREAD

**Issue by mengjieli0726** [kubernetes-csi/drivers#58]
1. Enable CSI by add the below parameters
```
API Server binary:
--allow-privileged=true
--feature-gates=CSIPersistentVolume=true,MountPropagation=true
--runtime-config=storage.k8s.io/v1alpha1=true

Controller-manager binary:
--feature-gates=CSIPersistentVolume=true

Kubelet:
--allow-privileged=true
--feature-gates=CSIPersistentVolume=true,MountPropagation=true
```
2. Deploy NFS driver according to https://github.com/kubernetes-csi/drivers/tree/master/pkg/nfs/deploy/kubernetes

```
[root@ib17b13 kubernetes]# kubectl  get sts
NAME                     DESIRED   CURRENT   AGE
csi-attacher-nfsplugin   1         1         22d
[root@ib17b13 kubernetes]# kubectl get ds
NAME                       DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
csi-nodeplugin-nfsplugin   2         2         2         2            2           <none>          22d

[root@ib17b13 kubernetes]# kubectl  get serviceaccount
NAME             SECRETS   AGE
csi-attacher     1         22d
csi-nodeplugin   1         22d
default          1         24d

[root@ib17b13 kubernetes]# kubectl get clusterrole|egrep "attach|csi"
csi-nodeplugin                                                         22d
external-attacher-runner                                               22d

[root@ib17b13 kubernetes]# kubectl  get clusterrolebinding|grep csi
csi-attacher-role                                      22d
csi-nodeplugin                                         22d
```

3. Deploy a Pod using CSI volume. Before starting this example, ensure to install NFS. 
```
[root@ib17b13 kubernetes]# showmount  -e
Export list for ib17b13:
/root/csi/nfs *
```

Modify pkg/nfs/examples/kubernetes/nginx.yaml, replace 
```
csi.volume.kubernetes.io/volume-attributes: '{"server": "10.10.10.10", "share": "share "}'  as 

csi.volume.kubernetes.io/volume-attributes: '{"server": "9.21.53.23", "share": "/root/csi/nfs"}'
```

Create nignx: 

````
# kubectl create -f nginx.yaml
persistentvolume "data-nfsplugin" created
persistentvolumeclaim "data-nfsplugin" created
pod "nginx" created
````
Check the nignx container nfs path, found mount nfs server source path is not correct.

```
# kubectl exec nginx -it  -- bash
```
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/2181539/36892672-717f6dcc-1e40-11e8-8ff7-fe3a366d1564.png">

The nfs mount source path should be 9.21.53.23:/root/csi/nfs not  9.21.53.23:/

**Comment by gyliu513** [comment]
@haoqing0110 can you help check?

**Comment by haoqing0110** [comment]
@gyliu513 @mengjieli0726 
The image **docker.io/k8scsi/nfsplugin:v0.1** used in [csi-attacher-nfsplugin.yaml](https://github.com/kubernetes-csi/drivers/blob/master/pkg/nfs/deploy/kubernetes/csi-attacher-nfsplugin.yaml) and [csi-nodeplugin-nfsplugin.yaml](https://github.com/kubernetes-csi/drivers/blob/master/pkg/nfs/deploy/kubernetes/csi-nodeplugin-nfsplugin.yaml) is out-of-date, inconsistent with code and example [nginx.yaml](https://github.com/kubernetes-csi/drivers/blob/master/pkg/nfs/examples/kubernetes/nginx.yaml)

Try to build image using [Dockerfile](https://github.com/kubernetes-csi/drivers/tree/master/pkg/nfs/dockerfile) with latest nfs driver code, source path defined in "share" will be mounted correctly.

@chakri-nelluri Can you help update official nfsplugin image with latest code? as well as image tag in [csi-attacher-nfsplugin.yaml](https://github.com/kubernetes-csi/drivers/blob/master/pkg/nfs/deploy/kubernetes/csi-attacher-nfsplugin.yaml) and [csi-nodeplugin-nfsplugin.yaml](https://github.com/kubernetes-csi/drivers/blob/master/pkg/nfs/deploy/kubernetes/csi-nodeplugin-nfsplugin.yaml). 
Thanks.

**Comment by haoqing0110** [comment]
@sbezverk  @xing-yang @rootfs Can you help on this update?

**Comment by sbezverk** [comment]
@gyliu513  @haoqing0110 I would suggest a couple of things:
1. Use v0.2.0 images from quay.io for external-provisioner/external-attacher/registrar (no need to build them, just make sure your yaml points to them)
2. build nfs image from the master of kubernetes-csi/drivers

**Comment by xing-yang** [comment]
Hi @haoqing0110, 
Can you try image links posted in this PR https://github.com/xing-yang/drivers/commit/dfe7d4e4e68994eabaf9a395cf0f4efd7d32874c?  The NFS plugin image is not in the official repo yet, but @rootfs has verified it works.  Thanks.

**Comment by xing-yang** [comment]
The image links under deploy/kubernetes/ are updated to point to v0.2.0 images now.  nginx.yaml is also updated.  Please test again.

**Comment by gyliu513** [comment]
@xing-yang one question, does the 0.2.0 means nfs driver version or the CSI version?

**Comment by xing-yang** [comment]
0.2.0 is the CSI version.  Our new images for NFS plugin, attacher, registrar are all tagged with 0.2.0 now.

**Comment by xing-yang** [comment]
Actually it is both.  NFS plugin version is also 0.2.0 now.
