### ISSUE TITLE
Error happens when building the `hostpath` driver

### ISSUE THREAD

**Issue by arm64b** [kubernetes-csi/drivers#71]
1. `git clone https://github.com/kubernetes-csi/drivers.git`
2. enter into the `drivers` folder
3. `# make hostpath` show below error:
```
if [ ! -d ./vendor ]; then dep ensure; fi
/bin/sh: 1: dep: not found
Makefile:35: recipe for target 'hostpath' failed
make: *** [hostpath] Error 127
```

Try to `# go get github.com/golang/dep`, but it fails at:
```
# github.com/golang/dep/vendor/github.com/boltdb/bolt
flag provided but not defined: -goversion
usage: compile [options] file.go...
...
```

**Comment by pohly** [comment]
@arm64b does https://stackoverflow.com/questions/46241177/in-gogland-i-get-flag-provided-but-not-defined-goversion-using-go-run help?

**Comment by arm64b** [comment]
Hello @pohly , yes, it's help. I messed up my go environment in my local machine (GOPATH), and after that, we need to `go get` this git repo, then it should be OK. Thanks for the information 👍

**Comment by arm64b** [comment]
This issue can be closed now.
