### ISSUE TITLE
Stability of NFS Driver (and other "samples")

### ISSUE THREAD

**Issue by colemickens** [kubernetes-csi/drivers#75]
This page (https://kubernetes-csi.github.io/docs/Drivers.html) lists NFS as an example driver, with "sample" stability status.

From `git`, it looks like it may be actively developed. What is the stability of the "sample" plugins such as NFS? Are there bigger plans for it? Is there something that makes it, in the authors opinions, unsuitable for production uses?

Thanks.

**Comment by chakri-nelluri** [comment]
@colemickens This is not throughly tested plugin and is currently unsupported and is not recommended for mission critical applications. We are always here though to help you if you see any issues.
