### ISSUE TITLE
Reorganization of drivers repo

### ISSUE THREAD

**Issue by lpabon** [kubernetes-csi/drivers#81]
**Overview**:
This repo was first created to be a location for example, non-production, drivers. Just a location on how they may be created. After some time, it has turned into a repo for real drivers. For this reason, these drivers should move onto their own repo with their own release cycles.

**Proposal**:
Here are a set of the proposals:

* First, make sure we tag and branch to keep around the older stuff.
* Rename _drivers_ to _driver-hostpath_ repo.
* Remove cinder, csi-common, flexadapter, iscsi, and nfs drivers and packages.
* Cleanup the documentation to just be the repo for hostpath and point to the csi-sanity mock driver as another example.

**Comment by saad-ali** [comment]
Xing: Moving csi-common will it break existing drivers? Are drivers using this? If so where should it be moved?

**Comment by saad-ali** [comment]
Move `flexadapter` to `kubernetes-csi/driver-flexadapter`
If `csi-common` is useful it should be `kubernetes-csi/csi-common`. Other wise move and mark deprecated.

**Comment by pohly** [comment]
Overall I'd prefer to keep ``kubernetes-csi/csi-common``.

**Comment by pohly** [comment]
Note that @shubheksha found an example that shows why we might want to avoid cut-and-paste: logGPRC logs secrets. If we want to fix that (undecided, see https://github.com/kubernetes-csi/external-provisioner/issues/82), then currently we would have to make the change in four places.

**Comment by pohly** [comment]
I have started vendoring csi-common into driver-registrar as part of the Jaeger tracing prototype, sharing both the logGRPC code and the Jaeger tracing support code:

* https://github.com/pohly/drivers/commits/jaeger-tracing
* https://github.com/pohly/driver-registrar/commits/jaeger-tracing

However, I'm not entirely happy with the setup. It is very cumbersome to make changes in csi-common and then use those changes in driver-registrar. One either has to hack in driver-registrar/vendor and copy changes back, or go through a commit/push/dep cycle with a locally set source constraint.

Has it been considered to put all code into the same repo?

Choosing the granularity of repos is always a tradeoff. Keeping each component in its own repo makes sense when they are technically independent and/or developed by different teams at a different pace. But I would argue that neither of these is the case here:
* once we start sharing code, the different apps become more closely coupled
* it's the same team making changes to all of them
* they get released at the same time
* integration testing in Kubernetes must be done with all four apps

**Comment by kfox1111** [comment]
@lpabon Looks like the reorg may have happened? can we create a repo for #85 yet?

**Comment by pohly** [comment]
kfox1111 <notifications@github.com> writes:
> @lpabon Looks like the reorg may have happened? can we create a repo
> for #85 yet?

No, the reorg is on hold at the moment. The Kubernetes CSI team decided
in one of the weekly meetings to continue development with one repo per
component. Your driver therefore should get its own repo.

**Comment by kfox1111** [comment]
Yeah, thats of what I'm asking. If it is to be in its own repo, can we get it created? github.com/kubernetes-csi/csi-driver-image?

Thanks,
Kevin

**Comment by kfox1111** [comment]
Oh. I see. the repos were created, but there isn't code in them yet. I can wait then.

**Comment by kfox1111** [comment]
Can someone please explain why this is stalled? I'd like to help if possible.
