### ISSUE TITLE
Does csi nfs driver support storageclass?

### ISSUE THREAD

**Issue by haoqing0110** [kubernetes-csi/drivers#86]
Examples of nfs driver here is using persistent volume, 
https://github.com/kubernetes-csi/drivers/blob/master/pkg/nfs/examples/kubernetes/nginx.yaml

Does nfs driver support dynamic provisioning currently?

**Comment by wqcheng** [comment]
@saad-ali 
hello，I also have this requirement. It is very troublesome to call csi to create PVC through pv. Can we support storageclass?

**Comment by wqcheng** [comment]
@haoqing0110 Do you have a good solution now?

**Comment by wqcheng** [comment]
@wongma7
