### ISSUE TITLE
Hostpath driver: csi-pod cannot be created

### ISSUE THREAD

**Issue by tonyfumonkey** [kubernetes-csi/drivers#99]
I am new to CSI and follows guideline here [https://kubernetes-csi.github.io/docs/Example.html](url). But when i create csi-pod as stated, it fails to be created.

> pod status

NAME      READY     STATUS              RESTARTS   AGE
csi-pod   3/4       RunContainerError   0          2m

> Error message

Events:
  Normal   Scheduled              1m    default-scheduler  Successfully assigned csi-pod to minikube
  Normal   SuccessfulMountVolume  1m    kubelet, minikube  MountVolume.SetUp succeeded for volume "socket-dir"
  Normal   SuccessfulMountVolume  1m    kubelet, minikube  MountVolume.SetUp succeeded for volume "mountpoint-dir"
  Normal   SuccessfulMountVolume  1m    kubelet, minikube  MountVolume.SetUp succeeded for volume "csi-service-account-token-4rwxz"
  Normal   Pulling                1m    kubelet, minikube  pulling image "quay.io/k8scsi/csi-provisioner:v0.3.0"
  Normal   Pulled                 1m    kubelet, minikube  Successfully pulled image "quay.io/k8scsi/csi-provisioner:v0.3.0"
  Normal   Created                1m    kubelet, minikube  Created container
  Normal   Started                1m    kubelet, minikube  Started container
  Normal   Pulling                1m    kubelet, minikube  pulling image "quay.io/k8scsi/driver-registrar:v0.2.0"
  Normal   Pulled                 1m    kubelet, minikube  Successfully pulled image "quay.io/k8scsi/driver-registrar:v0.2.0"
  Normal   Created                1m    kubelet, minikube  Created container
  Normal   Started                1m    kubelet, minikube  Started container
  Normal   Pulling                1m    kubelet, minikube  pulling image "quay.io/k8scsi/csi-attacher:v0.2.0"
  Normal   Pulled                 59s   kubelet, minikube  Successfully pulled image "quay.io/k8scsi/csi-attacher:v0.2.0"
  Normal   Created                59s   kubelet, minikube  Created container
  Normal   Started                59s   kubelet, minikube  Started container
  Normal   Pulling                59s   kubelet, minikube  pulling image "quay.io/k8scsi/hostpathplugin:v0.2.0"
  Normal   Pulled                 55s   kubelet, minikube  Successfully pulled image "quay.io/k8scsi/hostpathplugin:v0.2.0"
  Normal   Created                55s   kubelet, minikube  Created container
  Warning  Failed                 55s   kubelet, minikube  Error: failed to start container "hostpath-driver": Error response from daemon: OCI runtime create failed: open /var/run/docker/runtime-runc/moby/hostpath-driver/state.json: no such file or directory: unknown

> Env: MacOS High Sierra

> k8s version: 

`Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

> k8s env

minikube

> docker version: 

`Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true`

**Comment by kippandrew** [comment]
I've also run into this error, any clues as to what might be going on?

**Comment by aayushrangwala** [comment]
Ran into the same issue here with k8s environment: Microk8s

**Comment by doprdele** [comment]
Running into same issue
